# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 07:58
from __future__ import unicode_literals

import Artifactorial.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to=Artifactorial.models.get_path_name)),
                ('is_permanent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.TextField(default=Artifactorial.models.random_hash, max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('is_public', models.BooleanField(default=False)),
                ('ttl', models.IntegerField(default=90, help_text='Files TTL in days')),
                ('quota', models.IntegerField(default=1073741824, help_text='Size limit in Bytes')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Directories',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(default=Artifactorial.models.random_hash, max_length=32, unique=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artifactorial.Artifact')),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artifactorial.Directory'),
        ),
    ]
