# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artifactorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='quota',
            field=models.BigIntegerField(default=1073741824, help_text='Size limit in Bytes'),
        ),
    ]
