# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artifactorial', '0002_use_biginteger_for_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='path',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
